name = "guess-who-worker"
main = "index.js"
account_id = "67bee2df6e2fc0808ab6388427731ec5"
compatibility_date = "2025-11-19"

[durable_objects]
bindings = [
  { name = "ROOM", class_name = "Room" }
]
